name: Issue and PR Auto Comment Workflow

on:
  issues:
    types: [opened, closed]
  pull_request:
    types: [opened, closed, merged]

jobs:
  # Respond to new issues
  respond-to-new-issues:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Comment on new issue
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hey @${{ github.actor }}, Welcome to 💖TelMedSphere !!! 🎊
            Thanks for opening an issue! 🙌 Please wait for the issue to get reviewed. If it is relevant, it will get assigned to you.
            Happy Coding !!! ✨

  # Respond to closed issues
  respond-to-closed-issues:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Comment on closed issue
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
             Hello @${{ github.event.issue.user.login }}! Your issue #${{ github.event.issue.number }} has been closed.
             Thank you for your interest in 💖TelMedSphere !!! 🙌


  # Respond to merged PRs
  respond-to-merged-prs:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Comment on merged PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
           @${{ github.event.pull_request.user.login }} Congrats, Your pull request has been successfully merged 🥳🎉
            Thank you for your contribution to 💖TelMedSphere !!!
            Happy coding 🎊, Keep Contributing 🙌 !!! 

  # Respond to closed PRs (not merged)
  respond-to-closed-prs:
    if: github.event.action == 'closed' && github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - name: Comment on closed PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Hello @${{ github.event.pull_request.user.login }}, your PR #${{ github.event.pull_request.number }} has been closed without merging. 😞
            Don't be discouraged! Please feel free to address any review comments or reopen the PR if necessary.
            Thank you for your effort and interest in 💖TelMedSphere !!! 🙌

  # Respond to new PRs (Added Section)
  respond-to-new-prs:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Comment on new PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Hey @${{ github.actor }}, Welcome to 💖TelMedSphere !!! 🎊
            Thanks for raising a PR! Your effort makes this project better. 🙌
            Please wait for the PR to be reviewed.
            Happy Coding!! ✨

