name: Automate Issue and PR Responses

on:
  issues:
    types:
      - opened
      - closed
  pull_request:
    types:
      - opened
      - closed

permissions:
  issues: write
  pull-requests: write

jobs:
  respond-to-events:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Respond to new issues
      - name: Respond to new issues
        if: ${{ github.event.action == 'opened' && github.event_name == 'issues' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hey @${{ github.actor }}, Welcome to 💖TelMedSphere! 🎊
            Thanks for opening an issue! 🙌 Please wait for the issue to be assigned.
            Happy Coding!! ✨

      # Respond to closed issues
      - name: Respond to closed issues
        if: ${{ github.event.action == 'closed' && github.event_name == 'issues' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}! Your issue #${{ github.event.issue.number }} has been closed.
            Thank you for your contribution to 💖TelMedSphere!!! 🙌

      # Respond to new PRs
      - name: Respond to new PRs
        if: ${{ github.event.action == 'opened' && github.event_name == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Hey @${{ github.actor }}, Welcome to 💖TelMedSphere 🎊
            Thanks for your contribution! Your effort makes this project better. Keep it up! 🙌
            Please wait for the PR to be reviewed.
            Happy Coding!! ✨

      # Respond to merged PRs
      - name: Respond to merged PRs
        if: ${{ github.event.action == 'closed' && github.event.pull_request.merged == true }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            @${{ github.event.pull_request.user.login }} Congrats, Your pull request has been successfully merged 🥳🎉
            Thank you for your contribution to 💖TelMedSphere!!
            Happy coding 🎊, Keep Contributing 🙌 !!!
